services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
    depends_on:
      - php-fpm
    ports:
      - "80"
    networks:
      - fakebsod-app

  php-fpm:
    image: php:8.3-fpm-alpine
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - fakebsod-app

networks:
  fakebsod-app:
